"""
Script 7: Reflexión Crítica
Plantilla para reflexión personal sobre el proceso de análisis.
"""

from pathlib import Path

def generar_plantilla_reflexion(output_dir='../resultados'):
    """Genera plantilla para reflexión crítica"""
    
    Path(output_dir).mkdir(exist_ok=True)
    
    reflexion = []
    reflexion.append("=" * 100)
    reflexion.append("💭 REFLEXIÓN CRÍTICA SOBRE EL PROCESO DE ANÁLISIS")
    reflexion.append("=" * 100)
    reflexion.append("")
    reflexion.append("📝 INSTRUCCIONES:")
    reflexion.append("   Esta es una plantilla para tu reflexión PERSONAL.")
    reflexion.append("   Completa cada sección con tus propias palabras y experiencias.")
    reflexion.append("   La IA generó los scripts, pero TÚ debes reflexionar sobre el proceso.")
    reflexion.append("")
    reflexion.append("")
    
    # Pregunta 1
    reflexion.append("1️⃣ ¿QUÉ FUE LO MÁS DIFÍCIL DEL ANÁLISIS?")
    reflexion.append("-" * 100)
    reflexion.append("")
    reflexion.append("Escribe aquí tu respuesta:")
    reflexion.append("")
    reflexion.append("Ejemplos de aspectos difíciles:")
    reflexion.append("   • Entender qué método usar en cada caso")
    reflexion.append("   • Interpretar los resultados numéricos (autovalores, cargas, etc.)")
    reflexion.append("   • Decidir cuántos componentes/factores/clusters retener")
    reflexion.append("   • Comprender las diferencias entre ACP y AFE")
    reflexion.append("   • Dar sentido a los clusters (qué representa cada grupo)")
    reflexion.append("   • Elegir la variable categórica para análisis discriminante")
    reflexion.append("   • [TU RESPUESTA AQUÍ]")
    reflexion.append("")
    reflexion.append("")
    
    # Pregunta 2
    reflexion.append("2️⃣ ¿QUÉ DECISIONES TUVISTE QUE TOMAR TÚ?")
    reflexion.append("-" * 100)
    reflexion.append("")
    reflexion.append("Escribe aquí tu respuesta:")
    reflexion.append("")
    reflexion.append("Decisiones que DEBES tomar manualmente:")
    reflexion.append("   • ¿Cuántos componentes/factores retener? (aunque hay criterios, tú decides)")
    reflexion.append("   • ¿Cómo interpretar cada componente/factor? (darle un nombre/significado)")
    reflexion.append("   • ¿Cuántos clusters crear? (método del codo da guía, pero tú decides)")
    reflexion.append("   • ¿Qué significa cada cluster? (descripción sustantiva)")
    reflexion.append("   • ¿Qué variable usar para discriminante? (elegir la más relevante)")
    reflexion.append("   • ¿Qué método es mejor para TU caso específico?")
    reflexion.append("   • ¿Cómo presentar los resultados en el informe?")
    reflexion.append("   • [TUS DECISIONES AQUÍ]")
    reflexion.append("")
    reflexion.append("")
    
    # Pregunta 3
    reflexion.append("3️⃣ ¿EN QUÉ PARTE TE AYUDÓ LA IA?")
    reflexion.append("-" * 100)
    reflexion.append("")
    reflexion.append("Escribe aquí tu respuesta:")
    reflexion.append("")
    reflexion.append("Lo que la IA SÍ hizo:")
    reflexion.append("   • Generar código Python para cada análisis")
    reflexion.append("   • Crear funciones para cargar y preparar datos")
    reflexion.append("   • Implementar los algoritmos (PCA, AFE, K-means, LDA)")
    reflexion.append("   • Generar gráficos automáticos (scree plots, matrices, etc.)")
    reflexion.append("   • Calcular métricas estadísticas")
    reflexion.append("   • Crear tablas de resultados")
    reflexion.append("   • Estructurar el proyecto (carpetas, archivos)")
    reflexion.append("   • Generar plantillas de interpretación")
    reflexion.append("   • [TU RESPUESTA AQUÍ]")
    reflexion.append("")
    reflexion.append("")
    
    # Pregunta 4
    reflexion.append("4️⃣ ¿QUÉ NO PUEDE AUTOMATIZAR LA IA Y LO HICISTE TÚ MANUALMENTE?")
    reflexion.append("-" * 100)
    reflexion.append("")
    reflexion.append("Escribe aquí tu respuesta:")
    reflexion.append("")
    reflexion.append("Lo que la IA NO puede hacer (y TÚ debes hacer):")
    reflexion.append("")
    reflexion.append("   📌 INTERPRETACIÓN SUSTANTIVA:")
    reflexion.append("      • La IA calcula números, TÚ les das significado")
    reflexion.append("      • Ejemplo: PC1 tiene cargas altas en edad, peso, IMC")
    reflexion.append("        → TÚ decides si llamarlo 'Factor de Desarrollo Físico'")
    reflexion.append("")
    reflexion.append("   📌 DECISIONES CONTEXTUALES:")
    reflexion.append("      • ¿Son estos resultados coherentes con la teoría?")
    reflexion.append("      • ¿Tienen sentido en el contexto de tu estudio?")
    reflexion.append("      • ¿Hay outliers o errores en los datos?")
    reflexion.append("")
    reflexion.append("   📌 CRÍTICA METODOLÓGICA:")
    reflexion.append("      • ¿Es apropiado usar este método con estos datos?")
    reflexion.append("      • ¿Qué limitaciones tiene el análisis?")
    reflexion.append("      • ¿Qué supuestos se cumplen o no?")
    reflexion.append("")
    reflexion.append("   📌 REDACCIÓN DEL INFORME:")
    reflexion.append("      • Escribir introducción, métodos, discusión")
    reflexion.append("      • Explicar por qué elegiste cada método")
    reflexion.append("      • Discutir implicaciones de los resultados")
    reflexion.append("")
    reflexion.append("   📌 VALIDACIÓN:")
    reflexion.append("      • Revisar que los resultados sean correctos")
    reflexion.append("      • Verificar que los gráficos tengan sentido")
    reflexion.append("      • Comprobar que no hay errores lógicos")
    reflexion.append("")
    reflexion.append("   [TU RESPUESTA AQUÍ]")
    reflexion.append("")
    reflexion.append("")
    
    # Pregunta 5
    reflexion.append("5️⃣ ¿QUÉ APRENDISTE DEL PROCESO?")
    reflexion.append("-" * 100)
    reflexion.append("")
    reflexion.append("Escribe aquí tu respuesta:")
    reflexion.append("")
    reflexion.append("Reflexiona sobre:")
    reflexion.append("   • ¿Qué conceptos estadísticos aprendiste o reforzaste?")
    reflexion.append("   • ¿Cómo cambió tu comprensión de estos métodos?")
    reflexion.append("   • ¿Qué harías diferente la próxima vez?")
    reflexion.append("   • ¿Qué habilidades desarrollaste?")
    reflexion.append("   • ¿Cómo aplicarías esto en futuros proyectos?")
    reflexion.append("")
    reflexion.append("Aprendizajes técnicos:")
    reflexion.append("   • Diferencias entre métodos de reducción de dimensionalidad")
    reflexion.append("   • Cómo interpretar autovalores y cargas factoriales")
    reflexion.append("   • Cómo usar Python para análisis estadístico")
    reflexion.append("   • [TUS APRENDIZAJES AQUÍ]")
    reflexion.append("")
    reflexion.append("Aprendizajes sobre IA:")
    reflexion.append("   • La IA es una herramienta poderosa para automatizar cálculos")
    reflexion.append("   • Pero NO reemplaza el pensamiento crítico humano")
    reflexion.append("   • El analista debe entender QUÉ hace la IA y POR QUÉ")
    reflexion.append("   • La interpretación final siempre requiere juicio humano")
    reflexion.append("   • [TUS REFLEXIONES AQUÍ]")
    reflexion.append("")
    reflexion.append("")
    
    # División clara de responsabilidades
    reflexion.append("=" * 100)
    reflexion.append("🤖 vs 👤 DIVISIÓN DE TRABAJO: IA vs HUMANO")
    reflexion.append("=" * 100)
    reflexion.append("")
    
    reflexion.append("🤖 LO QUE HIZO LA IA:")
    reflexion.append("-" * 100)
    reflexion.append("   ✅ Generar código Python")
    reflexion.append("   ✅ Implementar algoritmos estadísticos")
    reflexion.append("   ✅ Calcular métricas numéricas")
    reflexion.append("   ✅ Crear gráficos y tablas")
    reflexion.append("   ✅ Estructurar archivos y carpetas")
    reflexion.append("   ✅ Generar plantillas y formatos")
    reflexion.append("")
    
    reflexion.append("👤 LO QUE DEBES HACER TÚ:")
    reflexion.append("-" * 100)
    reflexion.append("   ✅ Ejecutar los scripts y revisar resultados")
    reflexion.append("   ✅ INTERPRETAR los números (darles significado)")
    reflexion.append("   ✅ DECIDIR número de componentes/factores/clusters")
    reflexion.append("   ✅ NOMBRAR y DESCRIBIR componentes/factores/clusters")
    reflexion.append("   ✅ EVALUAR coherencia con teoría y contexto")
    reflexion.append("   ✅ CRITICAR limitaciones del análisis")
    reflexion.append("   ✅ REDACTAR el informe final")
    reflexion.append("   ✅ REFLEXIONAR sobre el proceso")
    reflexion.append("   ✅ APRENDER de los conceptos estadísticos")
    reflexion.append("")
    
    reflexion.append("=" * 100)
    reflexion.append("📝 IMPORTANTE:")
    reflexion.append("   ¡Completa esta reflexión con TUS PROPIAS PALABRAS!")
    reflexion.append("   No copies las sugerencias, úsalas solo como guía.")
    reflexion.append("   Tu profesor quiere saber TU experiencia personal.")
    reflexion.append("=" * 100)
    reflexion.append("")
    
    # Guardar
    reflexion_text = "\n".join(reflexion)
    print(reflexion_text)
    
    path = Path(output_dir) / 'plantilla_reflexion_critica.txt'
    with open(path, 'w', encoding='utf-8') as f:
        f.write(reflexion_text)
    
    print(f"\n💾 Plantilla guardada: {path}")
    print("\n⚠️  RECUERDA: Debes completar esta plantilla con tus propias reflexiones!")

def main():
    """Función principal"""
    print("=" * 100)
    print("💭 ANÁLISIS 4: PLANTILLA DE REFLEXIÓN CRÍTICA")
    print("=" * 100)
    print("")
    print("⚠️  Esta es una PLANTILLA que debes completar TÚ.")
    print("    La IA NO puede hacer esta parte por ti.")
    print("")
    
    generar_plantilla_reflexion()
    
    print("\n✅ ¡Plantilla de reflexión generada!")
    print("\n📋 PRÓXIMOS PASOS:")
    print("   1. Abre el archivo: resultados/plantilla_reflexion_critica.txt")
    print("   2. Lee cada pregunta cuidadosamente")
    print("   3. Escribe TUS propias respuestas (no copies las sugerencias)")
    print("   4. Sé honesto sobre tu experiencia")
    print("   5. Incluye esta reflexión en tu informe final")

if __name__ == "__main__":
    main()
